### ISSUE TITLE
Fix: code examples does not match with NameRegistry contract

### ISSUE THREAD

**Issue by Thibrac** [cairo-book/cairo-book#1045]
https://book.cairo-lang.org/ch14-01-00-contract-storage.html

Change code snippets on pages that rely on the NameRegistry contract (p14.1, p14.2, p14.13) to match the contract (p14).

**Comment by enitrat** [comment]
Hi @Thibrac, here's a proposal on how to do these things:

- Remove the NameRegistry contract example from https://book.cairo-lang.org/ch14-00-building-starknet-smart-contracts.html and put it in https://book.cairo-lang.org/ch14-02-contract-functions.html. It will only be used in ch14-02.

- Because we no longer need as many examples regarding storage in our NameRegistry contract, simplify the contract to only keep simple storage variables: remove `registrations`, the `get_registration_info` function. The goal of the contract is now to simply show all the different kind of functions, we can also remove events.

- Change the code examples in https://book.cairo-lang.org/ch14-02-contract-functions.html from `{{#include...}}` to`{{#rustdoc_include ...}}# to enable the small "expand" button

- Add a listing with the full `SimpleStorage` contract in https://book.cairo-lang.org/ch14-01-00-contract-storage.html (the one used in the isolated listings with hidden context)

Feel free to add any suggestion
