### ISSUE TITLE
Add a section on the Copy mechanism

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book#382]

**Comment by enitrat** [comment]
@wraitii I heard you would like to take this issue?

**Comment by wraitii** [comment]
![Sans-titre-2023-11-09-1039](https://github.com/cairo-book/cairo-book/assets/1927071/913debcc-e115-4887-821f-f106ecb69da2)

Started an Excalidraw: https://excalidraw.com/#room=e49f594e9f284668b8ea,Eud7vQQefDRFD7GQ-EO0RQ (and see image).

I think the core issue is that Cairo, unlike rust (but like Python / javascript /...) has 'fat-pointer' variables, instead of just being memory-cells.

If you explain that `Copy` in rust refers to the memory being copyable, but in Cairo refers to the variable being copyable, things make a little more sense.

I don't have much time right now, but might try to work on this at Istanbul / later
