### ISSUE TITLE
feat: add examples of smart contract testing

### ISSUE THREAD

**Issue by glihm** [cairo-book/cairo-book#416]
It can be helpful to add information about how to test smart contract, especially with the `contract_state_for_testing` to mock a contract state.

https://github.com/starkware-libs/cairo/blob/ee123b2b47a043a4e4ffe6b60d969fe0f1ae978e/crates/cairo-lang-starknet/cairo_level_tests/interoperability.cairo#L41

**Comment by enitrat** [comment]
Which format do you envision?
I think the Starknet foundry book will do a better job at this (and eventually we shouldn't rely on the native runner) 
https://foundry-rs.github.io/starknet-foundry/testing/testing_contract_internals.html

**Comment by glihm** [comment]
Hum, i was thinking to add a section in the testing chapter. But if we shouldn't rely on the test runner then it makes no sense to repeat the doc from sn foundry and just link to it.

In my head the Cairo test runner it still the "native" / no dependency testing framework which in my opinion is important.

But sn foundry will surely evolve faster with more cheatcode in the contract testing scope.

So we can add a small section about this, or we can redirect to sn foundry both are good. :)

**Comment by enitrat** [comment]
Let's do both - a succinct section about using the native test runner followed by an introduction and an example of testing with foundry, ending with a redirection to the foundry book.

**Comment by Mohiiit** [comment]
Hey, Can I pick this up?

**Comment by enitrat** [comment]
Please go ahead @Mohiiit - you're free on the format, but don't forget to
- Introduce the common cheatcodes to mock the current contract address / the caller address / block info / etc
- Testing patterns using both dispatchers and directly testing internal functions using a ContractState

The testing example  in [StarknetByExample](https://starknet-by-example.voyager.online/ch00/testing/contract-testing.html) already looks good to me. I think you could do something similar but with more details, especially regarding testing of internal functions. Instead of having the entire code in a single block, you can organize the page with subsections, for example

# Testing with Starknet Foundry
Introduce SN Foundry and link the SN Foundry book - and present the advantages of using SN Foundry

# Testing with the native Test Runner
Succint introduction of the cases where using the native runner is interesting

## Testing a deployed contract

### Deploying the contract to test

### Testing external functions using the dispatcher

### Mocking the caller address in the called contract

## Testing contract functions directly


I think this should cover pretty much everything

**Comment by Mohiiit** [comment]
should I add it as section 12.9?

**Comment by enitrat** [comment]
Sorry @Mohiiit I missed the message (was OOO). Have you started yet? Yes, you can add it as 12.9

**Comment by TAdev0** [comment]
@Mohiiit  are you still working on it? currently the appropriate place in the book would be 17.2. " Testing Smart Contracts with Starknet Foundry" , but it can be renamed ''Testing Smart Contracts'' simply to match the template @enitrat  provided

**Comment by FriendlyLifeguard** [comment]
Hello, can I take this if it is no longer being worked on?

**Comment by enitrat** [comment]
Hi, yes please go ahead!

**Comment by ebukizy1** [comment]
can i jump on this caught my interest since it open.. can i be assign this

**Comment by enitrat** [comment]
@FriendlyLifeguard is on it

**Comment by FriendlyLifeguard** [comment]
Hi, ran into some issues :( Going to be spending this entire week working on this.

**Comment by glihm** [comment]
> Hi, ran into some issues :( Going to be spending this entire week working on this.

What kind of issues? Do you need a hand on that?

**Comment by FriendlyLifeguard** [comment]
Currently asking eni for some help! : )

**Comment by TAdev0** [comment]
@FriendlyLifeguard  feel free to contact me as well if you need any assistance for your tests!

**Comment by FriendlyLifeguard** [comment]
@TAdev0 Thank you. How can I contact you?
