### ISSUE TITLE
Maintain Chapter 11 Advanced features

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#568]
- [x] should be renamed Advance Cairo (features)
- [x] Move custom data structures in this section
- [x] 11-1: maybe add precisions that there is no need to use the #[generate_trait] attribute here as it is just one implementation of Add<T> trait method of corelib
- [x] 11-2: allows -> allow
- [x] 11-3: update_with is a part of the extension trait for hash state accumulators called HashStateExTrait, this should be shortly mentioned with other traits, especially because update_with is used multiple times in the section
- [x] 11-3: A few errors with imports (pedersen instead of poseidon at some place)
- [x] 11-3: Serde and copy attributes are not necessary for StructToHash
- [x]  11-3: Serialization could be shortly introduced as it is used for the poseidon struct example 
- [x] 11-3: Advanced hashing : example of hashing a **struct** (instead of function) that contains a span<felt252>
- [x] 11-3: following trait**s** and function

**Comment by kwkr** [comment]
Hello @enitrat and @TAdev0 ! I allowed myself to fix some of the points that I could find from the list.
The points I wasn't able to fix/find:

11-1: maybe add precisions that there is no need to use the #[generate_trait] attribute here as it is just one implementation of Add trait method of corelib
 11-3: A few errors with imports (pedersen instead of poseidon at some place)
 11-3: Serde and copy attributes are not necessary for StructToHash

They might have been already fixed/moved.
