### ISSUE TITLE
Refactor: Rewrite 'Implementing a Trait on a type' and 'Implementing a trait, without writing its declaration' sections

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book#584]
Both sections are not accurate on trait implementation and method definitions in Cairo, and should be reworked : 

- Methods are defined on a non generic type, and the interface to call them can be automatically generated with the `#[generate_trait]` attribute, ie: 

```
struct Person {
    name: felt252,
}

trait Human {
    fn get_name(self: @Person) -> felt252;
}
impl HumanMethods of Human {
    fn get_name(self: @Person) -> felt252 {
        *self.name
    }
}
```

is the same as : 
```
#[generate_trait]
impl HumanMethods of Human {
    fn get_name(self: @Person) -> felt252 {
        *self.name
    }
}
```

- Trait implementations define a specific implementation for a specific type, given a generic interface, ie: 

```
trait Mammal<T> {
 fn get_height() -> u32;
}

impl MammalHuman of Mammal<Human>{
   fn get_height(self: @Human) -> u32 {self.height}
}
```

**Comment by enitrat** [comment]
yep, great! + this makes me realize why the `Trait` suffix is often required, although it doesn't really make sense to name a trait "Trait".

Consider the first example: ideally, you would like to do something like in rust where you can have the definition of methods associated to a type
```rust
struct Human {
    name: felt252,
}

impl Human {
    fn get_name(self: @Human) -> felt252 {
        *self.name
    }
}
```

But in cairo, impls are always linked to a trait. So the equivalent would be 

```rust
struct Human {
    name: felt252,
}

impl HumanImpl of HumanTrait {
    fn get_name(self: @Human) -> felt252 {
        *self.name
    }
}
```

Because the type name is the type name, it cannot be used for either the impl name nor the trait name. So we have to give them suffixes to differentiate them. 

Whereas, for trait implementation, the name of the trait is not linked to a specific type, and thus there's no conflict. I'm not sure how to present things, but I guess the convention could be

- Implementation of a type (= define a type's methods) => impl TypeImpl of TypeTrait
- Trait implementation => impl TypeTrait of Trait

e.g.

```rust
trait Shape<T>{
fn area(self: @T) -> u32;
}

impl CircleShape of Shape<Circle> {}

impl RectangleShape of Shape<Rectangle>{}
```

So the actionable thing for this issue is to imo:
- Remove the  "Implementing a trait, without writing its declaration" in the traits section. I don't think it makes sense to implement a trait that has no declaration, as you wont be able to benefic from any generic effects, it's just defining methods associated to a type (and we have section for this that we can make clearer with this reasoning )
- Incorporate this reasoning to the Method Syntax chapter

**Comment by remybar** [comment]
Everything is clear to me, I will work on it 👍 

To me, implementing a generic trait for a type is a way of adding new behaviour for that type, as when we extends some interfaces such as Drawable, Iterable, etc ... for a class, so using [generate_trait] in this case is effectively nonsense.

```rust
struct Circle {
    radius: u32
}

struct Rectangle {
    width: u32,
    height: u32
}

trait Drawable<T>{
    fn draw(self: @T);
}

impl CircleDrawable of Drawable<Circle> {
    fn draw(self: @Circle){
        println!("I'm a funny circle !")
    }
}

impl RectangleDrawable of Drawable<Rectangle>{
    fn draw(self: @Rectangle){
        println!("I'm a strong rectangle !")
    }
}
```

When we just want to add some methods to a type, it seems useless to me to declare and then implement a trait, as the trait declaration won't be used anymore. In this case, using `[generate_trait]` makes the code easier to read.

```rust
#[generate_trait]
impl RectangleMethods of RectangleTrait {
    fn area(self: @Rectangle) -> u32 {
        *self.width * *self.height
    }
}
```

Anyway, I will read carefully both chapters "Traits in Cairo" and "Methods syntax" to try to improve that ;-)

**Comment by enitrat** [comment]
yes, exactly!

**Comment by TAdev0** [comment]
#600 

@enitrat  I close this issue as completed

Thank you @remybar  !
